hack/system: build before switch and add dry-build
Signed-off-by: Vincent Demeester <vincent@sbr.pm>

diff --git a/hack/system b/hack/system
--- a/hack/system
+++ b/hack/system
@@ -19,6 +19,16 @@ function set_work_dir() {
     fi
 }
 
+function dry-build() {
+    [ "$#" -eq 0 ] || error "build"
+    set_work_dir
+    local machine
+    machine="$(hostname)"
+    unset NIX_PATH
+    nix-build --dry-run --out-link "$WORK_DIR" -A "$machine" ||
+        error "Failed to build system"
+}
+
 function build() {
     [ "$#" -eq 0 ] || error "build"
     set_work_dir
@@ -31,6 +41,7 @@ function build() {
 
 function switch() {
     [ "$#" -eq 0 ] || error "switch"
+    build
     set_work_dir
     local switch_bin="$WORK_DIR/bin/switch-to-configuration"
     sudo nix-env --set \
